apps/main/urls.py
# coding: utf-8

# Django import
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="index"),
    path('mon-compte/creer/patient/', views.PatientSignupView.as_view(), name='patient_signup'),
    path('mon-compte/creer/confirmation/', views.signup_user_confirmation, name='signup_user_confirmation'),
]

django-concurrency-test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('apps.main.urls', namespace='main')),
    path('mon-compte/', auth_views.LoginView.as_view(
        template_name='main/login.html'), name='login'),
    path('mon-compte/login/', auth_views.LoginView.as_view(
        template_name='main/login.html'), name='login'),
    path('mon-compte/logout/', auth_views.LogoutView.as_view(
        template_name='main/logged_out.html'), name='logout'),
    path('mon-compte/reset-password/', auth_views.PasswordResetView.as_view(
        template_name='main/password_reset_form.html'), name='password_reset'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path("__debug__", include(debug_toolbar.urls)),
    ]

templates/account.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Django concurrency test{% endblock title %}</title>
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}"/>
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/mstile-144x144.png' %}">
    <meta name="msapplication-config" content="{% static 'favicon/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- Font -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="content-language" content="fr">
    <meta name="language" content="fr">
    <meta name="copyright" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="format-detection" content="telephone=no">
    <!-- CSS files -->
    <link href="{% static 'css/app.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="page">
      <div class="site-container-account">
        <div class="content">
          {% block content %}
          {% endblock content %}
        </div>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    <script src="{% static 'js/app.min.js' %}" type="text/javascript"></script>
    {% block extra_js %}{% endblock extra_js %}
    {% block extra_js_no_compress %}{% endblock extra_js_no_compress %}
  </body>
</html>

templates/default.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Django concurrency test{% endblock title %}</title>
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}"/>
    <!-- Font -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="content-language" content="fr">
    <meta name="language" content="fr">
    <meta name="copyright" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="format-detection" content="telephone=no">
    <!-- CSS files -->
    <link href="{% static 'css/app.min.css' %}" rel="stylesheet">
    {% block extra_css %}{% endblock extra_css %}
  </head>
  <body>
    <div class="page">
      <div class="site-container">
        {% include 'navbar.html' %}
        <section class="content">
          {% block content %}
          {% endblock content %}
        </section>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js" integrity="sha256-/ijcOLwFf26xEYAjW75FizKVo5tnTYiQddPZoLUHHZ8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/js/all.min.js" integrity="sha512-YSdqvJoZr83hj76AIVdOcvLWYMWzy6sJyIMic2aQz5kh2bPTd9dzY3NtdeEAzPp/PhgZqr4aJObB3ym/vsItMg==" crossorigin="anonymous"></script>
    <script src="{% static 'js/app.min.js' %}" type="text/javascript"></script>
    {% block extra_js %}{% endblock extra_js %}
    {% block extra_js_no_compress %}{% endblock extra_js_no_compress %}
  </body>
</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'main:index' %}" title="Accueil">
    Home
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse text-right" id="navbar">
    <ul class="navbar-nav mr-2 mr-lg-auto">
    </ul>
    <span class="navbar-text mt-3 mt-lg-0">
      <ul class="navbar-nav mr-auto">
        <li>
          <ul class="d-block d-lg-inline-flex m-0 p-0 list-unstyled">
            <li class="nav-item dropdown">
              <button class="btn btn-outline-danger mx-2 my-1 dropdown-toggle" id="navbar_dropdown4" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Créer un compte
              </button>
              <div class="dropdown-menu" aria-labelledby="navbar_dropdown4">
                <a class="dropdown-item text-dark" href="{% url 'main:patient_signup' %}">Patient</a>
              </div>
            </li>
          </ul>
          <a href="{% url 'login'%}"><button type="button" class="btn btn-outline-primary mx-2 my-1" title="Me connecter">Me connecter</button></a>
        </li>
      </ul>
    </span>
  </div>
</nav>